import type {Metadata} from "next";
import "./globals.css";
import dynamic from "next/dynamic";

const LeftSidebar = dynamic(() => import('@/components/left-sidebar'))


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <section className="main__wrapper">
      <LeftSidebar/>
      <div className='right__container'>
        {children}
      </div>
    </section>
    </body>
    </html>
  );
}
